/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package braces.gui.page;

import braces.controller.impl.KhachHangControllerImpl;
import braces.controller.impl.PhieuXuatControllerImpl;
import braces.controller.impl.TaiKhoanControllerImpl;
import braces.dao.impl.KhachHangDAOImpl;
import braces.dao.impl.PhieuXuatDAOImpl;
import braces.dao.impl.TaiKhoanDAOImpl;
import braces.entity.NhaCungCap;
import braces.entity.PhieuXuat;
import braces.entity.SanPham;
import braces.gui.MainLayout;
import braces.gui.dialog.DetailExportBill;
import braces.util.Formatter;
import braces.util.JTableExporter;
import braces.util.JTableUtilities;
import braces.util.MessageDialog;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dialog;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import lombok.Getter;

/**
 *
 * @author Braces
 */
@Getter
public class ExportPage extends javax.swing.JPanel {

    private MainLayout main;
    PhieuXuatControllerImpl ct = new PhieuXuatControllerImpl(new PhieuXuatDAOImpl());
    List<PhieuXuat> list = List.of();
    TaiKhoanControllerImpl ctTK = new TaiKhoanControllerImpl(new TaiKhoanDAOImpl());
    KhachHangControllerImpl ctKH = new KhachHangControllerImpl(new KhachHangDAOImpl());

    /**
     * Creates new form ImportPage
     */
    public ExportPage() {
        initComponents();
    }

    public ExportPage(MainLayout main) {
        this.main = main;
        initComponents();
        init();
    }

    public void init() {
        list = ct.getAll();
        loadTable();
        JTableUtilities.setCellsAlignment(table, SwingConstants.CENTER);
    }

    public void loadTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        for (PhieuXuat px : list) {
            model.addRow(new Object[]{
                px.getMaPhieuXuat(),
                Formatter.FormatDate(px.getThoiGian()),
                ctTK.getById(px.getNguoiTaoPhieuXuat()).get().getTenNv(),
                ctKH.getById(px.getMaKH()).get().getTenKhachHang(),
                Formatter.formatVND((double) px.getTongTien())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel2 = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        lblTable = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFromPrice = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtToPrice = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        headerPanel2.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 2, true));
        headerPanel2.setPreferredSize(new java.awt.Dimension(1294, 103));
        headerPanel2.setLayout(new java.awt.BorderLayout());

        actionPanel.setBackground(new java.awt.Color(255, 255, 255));
        actionPanel.setPreferredSize(new java.awt.Dimension(700, 100));
        actionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 5));

        btnAdd.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAdd.setIcon(new FlatSVGIcon("svg/add.svg"));
        btnAdd.setText("THÊM");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setPreferredSize(new java.awt.Dimension(90, 90));
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        actionPanel.add(btnAdd);

        btnInfo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnInfo.setIcon(new FlatSVGIcon("svg/info.svg"));
        btnInfo.setText("INFO");
        btnInfo.setBorder(null);
        btnInfo.setBorderPainted(false);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.setFocusPainted(false);
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfo.setPreferredSize(new java.awt.Dimension(90, 90));
        btnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        actionPanel.add(btnInfo);

        btnExport.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnExport.setIcon(new FlatSVGIcon("svg/excel.svg"));
        btnExport.setText("EXPORT");
        btnExport.setBorder(null);
        btnExport.setBorderPainted(false);
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.setFocusPainted(false);
        btnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExport.setPreferredSize(new java.awt.Dimension(90, 90));
        btnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        actionPanel.add(btnExport);

        headerPanel2.add(actionPanel, java.awt.BorderLayout.WEST);

        add(headerPanel2, java.awt.BorderLayout.PAGE_START);

        tablePanel.setBackground(new java.awt.Color(243, 243, 243));
        tablePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 2, true));
        tablePanel.setLayout(new java.awt.BorderLayout(2, 0));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Thời gian", "Tên nhân viên", "Tên khách hàng", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        tablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel9.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel9.setLayout(new java.awt.BorderLayout());

        lblTable.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblTable.setForeground(new java.awt.Color(255, 255, 255));
        lblTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTable.setText("THÔNG TIN PHIẾU XUẤT");
        jPanel9.add(lblTable, java.awt.BorderLayout.CENTER);

        tablePanel.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 8));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 16, 8));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Từ số tiền");
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel13.add(jLabel4);

        txtFromPrice.setPreferredSize(new java.awt.Dimension(170, 40));
        txtFromPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromPriceActionPerformed(evt);
            }
        });
        txtFromPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFromPriceKeyReleased(evt);
            }
        });
        jPanel13.add(txtFromPrice);

        jPanel10.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 16, 8));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Đến số tiền:");
        jLabel5.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel14.add(jLabel5);

        txtToPrice.setPreferredSize(new java.awt.Dimension(170, 40));
        txtToPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtToPriceKeyReleased(evt);
            }
        });
        jPanel14.add(txtToPrice);

        jPanel10.add(jPanel14);

        tablePanel.add(jPanel10, java.awt.BorderLayout.LINE_START);

        add(tablePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        main.setPanel(new CreateExportBillPage(this));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        int row = table.getSelectedRow();
        if (row == -1) {
            MessageDialog.error(this, "Chưa chọn dòng để xem");
            return;
        }
        int id = (int) table.getValueAt(row, 0);
        Optional<PhieuXuat> px = ct.getById(id);
        Dialog dialog = new DetailExportBill(null, true, px.get());
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.setResizable(false);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        JTableExporter.exportJTableToExcel(table);
    }//GEN-LAST:event_btnExportActionPerformed

    private void txtFromPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFromPriceKeyReleased
        if (txtFromPrice.getText().isEmpty()) {
            return;
        }
        if (txtToPrice.getText().isEmpty()) {
            return;
        }
        long from = Long.parseLong(txtFromPrice.getText());
        long to = Long.parseLong(txtToPrice.getText());
        if (from <= to) {
            list = ct.getFilterTable(1, from, to);
        }
        loadTable();
    }//GEN-LAST:event_txtFromPriceKeyReleased

    private void txtToPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToPriceKeyReleased
        if (txtFromPrice.getText().isEmpty()) {
            return;
        }
        if (txtToPrice.getText().isEmpty()) {
            return;
        }
        long from = Long.parseLong(txtFromPrice.getText());
        long to = Long.parseLong(txtToPrice.getText());
        if (from <= to) {
            System.out.println("1");
            list = ct.getFilterTable(1, from, to);
        }
        loadTable();
    }//GEN-LAST:event_txtToPriceKeyReleased

    private void txtFromPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromPriceActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnInfo;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTable;
    private javax.swing.JTable table;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTextField txtFromPrice;
    private javax.swing.JTextField txtToPrice;
    // End of variables declaration//GEN-END:variables
}
