/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package braces.gui.page;

import braces.controller.impl.LichSuControllerImpl;
import braces.dao.impl.LichSuDAOImpl;
import braces.dto.LichSuDTO;
import braces.util.Formatter;
import braces.util.JTableUtilities;
import braces.util.MessageDialog;
import java.util.Calendar;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Braces
 */
public class ExportHistoryPage extends javax.swing.JPanel {

    /**
     * Creates new form ImportHistoryPage
     */
    LichSuControllerImpl ct = new LichSuControllerImpl(new LichSuDAOImpl());
    List<LichSuDTO> list = List.of();

    public ExportHistoryPage() {
        initComponents();

        init();
    }

    void init() {
        JTableUtilities.setCellsAlignment(table, SwingConstants.CENTER);
        jdcEndDate.setDate(new Date());
        Calendar calNow = Calendar.getInstance();
        calNow.add(Calendar.MONTH, -1);
        Date dateBeforeAMonth = calNow.getTime();
        jdcStartDate.setDate(dateBeforeAMonth);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        table.setAutoCreateRowSorter(true);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        sorter.setComparator(3, Comparator.comparingDouble(Formatter::unformatVND)); 
        sorter.setComparator(4, Comparator.comparingDouble(Formatter::unformatVND));
        table.setRowSorter(sorter);

    }

    void loadTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (LichSuDTO ls : list) {
            Object[] rowData = {ls.getTenSanPham(), ls.getMaPhienBan(), ls.getSoLuong(), 
                Formatter.formatVND(ls.getGiaTien()), Formatter.formatVND((long) ls.getSoLuong() * ls.getGiaTien())};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jdcStartDate = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jdcEndDate = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        lblTable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1130, 480));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 8));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 16, 8));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Từ ngày");
        jLabel5.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel10.add(jLabel5);

        jdcStartDate.setPreferredSize(new java.awt.Dimension(170, 40));
        jdcStartDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcStartDatePropertyChange(evt);
            }
        });
        jPanel10.add(jdcStartDate);

        jPanel4.add(jPanel10);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 16, 8));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Đến ngày");
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel9.add(jLabel4);

        jdcEndDate.setPreferredSize(new java.awt.Dimension(170, 40));
        jdcEndDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcEndDatePropertyChange(evt);
            }
        });
        jPanel9.add(jdcEndDate);

        jPanel4.add(jPanel9);

        add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel5.setLayout(new java.awt.BorderLayout());

        lblTable.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblTable.setForeground(new java.awt.Color(255, 255, 255));
        lblTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTable.setText("THÔNG TIN SẢN PHẨM ĐÃ XUẤT RA");
        jPanel5.add(lblTable, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Mã phiên bản", "Số lượng", "Đơn giá", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jdcStartDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcStartDatePropertyChange
        // TODO add your handling code here:
        try {
            if (jdcStartDate.getDate() != null && jdcEndDate != null) {
                list = ct.getLichSuXuat(jdcStartDate.getDate(), jdcEndDate.getDate());
                loadTable();
            }
        } catch (Exception e) {
            MessageDialog.warring(this, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc");
        }
    }//GEN-LAST:event_jdcStartDatePropertyChange

    private void jdcEndDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcEndDatePropertyChange
        // TODO add your handling code here:
        try {
            if (jdcStartDate.getDate() != null && jdcEndDate != null) {
                list = ct.getLichSuXuat(jdcStartDate.getDate(), jdcEndDate.getDate());
                loadTable();
            }
        } catch (Exception e) {
            MessageDialog.warring(this, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc");
        }
    }//GEN-LAST:event_jdcEndDatePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcEndDate;
    private com.toedter.calendar.JDateChooser jdcStartDate;
    private javax.swing.JLabel lblTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
