/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package braces.gui.page;

/**
 *
 * @author Braces
 */
public class HistoryPage extends javax.swing.JPanel {

    /**
     * Creates new form History
     */
    public HistoryPage() {
        initComponents();
        initLayout();
    }
  private void initLayout() {

        tabPane.addTab("Lịch sử sản phẩm nhập", new ImportHistoryPage());
        tabPane.addTab("Lịch sử sản phẩm xuất", new ExportHistoryPage());

        this.add(tabPane);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(235, 230, 245));
        setLayout(new java.awt.BorderLayout());

        tabPane.setPreferredSize(new java.awt.Dimension(100, 30));
        add(tabPane, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
