/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package braces.gui.page;

import braces.dao.impl.ThongKeDAOImpl;
import braces.dto.ThongKeDTO;
import braces.gui.chart.ModelChart;
import braces.util.Formatter;
import braces.util.JTableExporter;
import braces.util.JTableUtilities;
import java.awt.Color;
import java.time.Year;
import java.util.Comparator;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Braces
 */
public class MonthlyStatsPage extends javax.swing.JPanel {

    /**
     * Creates new form StatsDaily
     */
    ThongKeDAOImpl tk = new ThongKeDAOImpl();
    List<ThongKeDTO> list = List.of();

    public MonthlyStatsPage() {
        initComponents();
        init();
    }

    void init() {
        JTableUtilities.setCellsAlignment(table, SwingConstants.CENTER);
        chart.addLegend("Chi ra", new Color(244, 67, 54));
        chart.addLegend("Thu vào", new Color(76, 175, 80));
        int currentYear = Year.now().getValue();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        sorter.setComparator(3, Comparator.comparingDouble(Formatter::unformatVND));
        sorter.setComparator(4, Comparator.comparingDouble(Formatter::unformatVND));
        table.setRowSorter(sorter);
        txtYear.setValue(currentYear);
    }

    void loadChart() {
        chart.clear();
        double sum_doanhthu = 0;
        double sum_chiphi = 0;
        for (int thang = 0; thang < list.size(); thang++) {
            sum_doanhthu = list.get(thang).getTongTienXuat();
            sum_chiphi = list.get(thang).getTongTienNhap();
            chart.addData(new ModelChart("Tháng " + (thang+1), new double[]{sum_chiphi, sum_doanhthu}));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblChart1 = new javax.swing.JLabel();
        txtYear = new com.toedter.components.JSpinField();
        btnStatistic = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        chart = new braces.gui.chart.Chart();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jPanel1.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel5.setBackground(new java.awt.Color(247, 247, 247));
        jPanel5.setPreferredSize(new java.awt.Dimension(1188, 30));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 0));

        lblChart1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblChart1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChart1.setText("Năm");
        lblChart1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblChart1.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel5.add(lblChart1);

        txtYear.setPreferredSize(new java.awt.Dimension(80, 26));
        jPanel5.add(txtYear);

        btnStatistic.setBackground(new java.awt.Color(51, 153, 255));
        btnStatistic.setForeground(new java.awt.Color(204, 255, 255));
        btnStatistic.setText("Thống kê");
        btnStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticActionPerformed(evt);
            }
        });
        jPanel5.add(btnStatistic);

        btnExport.setBackground(new java.awt.Color(0, 153, 102));
        btnExport.setForeground(new java.awt.Color(204, 255, 204));
        btnExport.setText("Xuất excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        jPanel5.add(btnExport);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(456, 300));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Năm", "Số lượng sản phẩm nhập", "Số lượng sản phẩm xuất", "Tổng só tiền nhập", "Tổng số tiền xuất"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Long.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel2.add(chart, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticActionPerformed
        list = tk.thongKeTheoThang(txtYear.getValue());
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (ThongKeDTO tkdto : list) {
            Object[] rowData = {tkdto.getThoiGian(), tkdto.getSoLuongNhap(), tkdto.getSoLuongXuat(),
                Formatter.formatVND(tkdto.getTongTienNhap()), Formatter.formatVND(tkdto.getTongTienXuat())};
            model.addRow(rowData);
        }
        loadChart();
    }//GEN-LAST:event_btnStatisticActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        JTableExporter.exportJTableToExcel(table);
    }//GEN-LAST:event_btnExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnStatistic;
    private braces.gui.chart.Chart chart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChart1;
    private javax.swing.JTable table;
    private com.toedter.components.JSpinField txtYear;
    // End of variables declaration//GEN-END:variables
}
