/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package braces.gui.page;

import braces.controller.impl.SanPhamControllerImpl;
import braces.dao.SanPhamDAO;
import braces.dao.impl.SanPhamDAOImpl;
import braces.entity.KhachHang;
import braces.entity.NhaCungCap;
import braces.entity.SanPham;
import braces.gui.MainLayout;
import braces.gui.dialog.CreateProductDialog;
import braces.gui.dialog.InfoProductDialog;
import braces.gui.dialog.EditProductDialog;
import braces.gui.dialog.EditSupplierDialog;
import braces.gui.dialog.ModelDialog;
import braces.gui.dialog.PropertiesDialog;
import braces.util.JTableExporter;
import braces.util.JTableUtilities;
import braces.util.MessageDialog;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import lombok.Getter;

@Getter
public class ProductPage extends javax.swing.JPanel {

    SanPhamControllerImpl ct = new SanPhamControllerImpl(new SanPhamDAOImpl());
    List<SanPham> list = List.of();
    MainLayout main;

    public ProductPage() {
        initComponents();
        init();
    }

    public void init() {
        list = ct.getAll();
        loadTable();
        JTableUtilities.setCellsAlignment(table, SwingConstants.CENTER);
        String[] searchType = {"Tất cả", "Mã", "Tên", "Xuất xứ", "Chip", "Mã kho"};
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(searchType);
        cboSearchType.setModel(model);
    }

    public void loadTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (SanPham sp : list) {
            Object[] row = {sp.getMaSP(), sp.getTenSanPham(), sp.getXuatXu(), sp.getChipXuLy(), sp.getMaKhuVucKho()};
            model.addRow(row);
        }
    }

    public ProductPage(MainLayout main) {
        this.main = main;
        initComponents();
        init();
    }

    void info(int row) {
        int id = (int) table.getValueAt(row, 0);
        Optional<SanPham> ncc = ct.getById(id);
        Dialog dialog = new InfoProductDialog(null, true, ncc.get());
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setVisible(true);

    }

    void model(int row) {
        int id = (int) table.getValueAt(row, 0);
        Dialog dialog = new ModelDialog(null, true, id);
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setVisible(true);
    }

    void properties(int row) {
        int id = (int) table.getValueAt(row, 0);
        Dialog dialog = new PropertiesDialog(null, true, id);
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setVisible(true);
    }

    void edit(int row) {
        int id = (int) table.getValueAt(row, 0);
        Optional<SanPham> ncc = ct.getById(id);
        Dialog dialog = new EditProductDialog(null, true, this, ncc.get());
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setVisible(true);
    }

    void delete(int row) {
        int id = (int) table.getValueAt(row, 0);
        if (MessageDialog.confirm(this, "Bạn có chắc chắn xóa dòng này?", "Xóa")) {
            ct.deleteById(id);
            MessageDialog.info(this, "Xóa thành công!");
            list = ct.getAll();
            loadTable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cboSearchType = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnReload = new javax.swing.JButton();
        actionPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnModel = new javax.swing.JButton();
        btnProperties = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        lblTable = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1130, 400));
        setPreferredSize(new java.awt.Dimension(1130, 800));
        setLayout(new java.awt.BorderLayout());

        headerPanel2.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 2, true));
        headerPanel2.setPreferredSize(new java.awt.Dimension(1294, 103));
        headerPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(590, 100));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 16, 24));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(370, 50));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        cboSearchType.setToolTipText("");
        cboSearchType.setPreferredSize(new java.awt.Dimension(100, 40));
        cboSearchType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSearchTypeItemStateChanged(evt);
            }
        });
        jPanel8.add(cboSearchType);

        txtSearch.setToolTipText("Tìm kiếm");
        txtSearch.setPreferredSize(new java.awt.Dimension(200, 40));
        txtSearch.setSelectionColor(new java.awt.Color(230, 245, 245));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel8.add(txtSearch);

        btnReload.setIcon(new FlatSVGIcon("svg/refresh.svg"));
        btnReload.setToolTipText("Làm mới");
        btnReload.setBorder(null);
        btnReload.setBorderPainted(false);
        btnReload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReload.setFocusPainted(false);
        btnReload.setFocusable(false);
        btnReload.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReload.setPreferredSize(new java.awt.Dimension(40, 40));
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        jPanel8.add(btnReload);

        jPanel7.add(jPanel8);

        headerPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        actionPanel.setBackground(new java.awt.Color(255, 255, 255));
        actionPanel.setPreferredSize(new java.awt.Dimension(700, 100));
        actionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 5));

        btnAdd.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAdd.setIcon(new FlatSVGIcon("svg/add.svg"));
        btnAdd.setText("THÊM");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setPreferredSize(new java.awt.Dimension(90, 90));
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        actionPanel.add(btnAdd);

        btnUpdate.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpdate.setIcon(new FlatSVGIcon("svg/edit.svg"));
        btnUpdate.setText("SỬA");
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setPreferredSize(new java.awt.Dimension(90, 90));
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        actionPanel.add(btnUpdate);

        btnDelete.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDelete.setIcon(new FlatSVGIcon("svg/delete.svg"));
        btnDelete.setText("XÓA");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 90));
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        actionPanel.add(btnDelete);

        btnInfo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnInfo.setIcon(new FlatSVGIcon("svg/info.svg"));
        btnInfo.setText("INFO");
        btnInfo.setBorder(null);
        btnInfo.setBorderPainted(false);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.setFocusPainted(false);
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfo.setPreferredSize(new java.awt.Dimension(90, 90));
        btnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        actionPanel.add(btnInfo);

        btnExport.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnExport.setIcon(new FlatSVGIcon("svg/excel.svg"));
        btnExport.setText("EXPORT");
        btnExport.setBorder(null);
        btnExport.setBorderPainted(false);
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.setFocusPainted(false);
        btnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExport.setPreferredSize(new java.awt.Dimension(90, 90));
        btnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        actionPanel.add(btnExport);

        btnModel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModel.setIcon(new FlatSVGIcon("svg/version.svg"));
        btnModel.setText("PHIÊN BẢN");
        btnModel.setBorder(null);
        btnModel.setBorderPainted(false);
        btnModel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModel.setFocusPainted(false);
        btnModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModel.setPreferredSize(new java.awt.Dimension(90, 90));
        btnModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });
        actionPanel.add(btnModel);

        btnProperties.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnProperties.setIcon(new FlatSVGIcon("svg/properties.svg"));
        btnProperties.setText("THUỘC TÍNH");
        btnProperties.setBorder(null);
        btnProperties.setBorderPainted(false);
        btnProperties.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProperties.setFocusPainted(false);
        btnProperties.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProperties.setPreferredSize(new java.awt.Dimension(90, 90));
        btnProperties.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropertiesActionPerformed(evt);
            }
        });
        actionPanel.add(btnProperties);

        headerPanel2.add(actionPanel, java.awt.BorderLayout.WEST);

        add(headerPanel2, java.awt.BorderLayout.PAGE_START);

        tablePanel.setBackground(new java.awt.Color(243, 243, 243));
        tablePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 2, true));
        tablePanel.setLayout(new java.awt.BorderLayout(2, 0));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên sản phẩm", "Xuất xứ", "Chip xử lí", "Khu vực kho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        tablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel9.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel9.setLayout(new java.awt.BorderLayout());

        lblTable.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblTable.setForeground(new java.awt.Color(255, 255, 255));
        lblTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTable.setText("THÔNG TIN SẢN PHẨM");
        jPanel9.add(lblTable, java.awt.BorderLayout.CENTER);

        tablePanel.add(jPanel9, java.awt.BorderLayout.NORTH);

        add(tablePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String type = (String) cboSearchType.getSelectedItem();
        list = ct.getSearchTable(txtSearch.getText(), type);
        loadTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        txtSearch.setText("");
        cboSearchType.setSelectedIndex(0);
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Dialog dialog = new CreateProductDialog(null, true, this);
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = table.getSelectedRow();
        if (row == -1) {
            MessageDialog.error(this, "Chưa chọn dòng để chỉnh sửa");
            return;
        }
        edit(row);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int row = table.getSelectedRow();
            if (row == -1) {
                MessageDialog.error(this, "Vui lòng chọn dòng cần thực hiện!");
                return;
            }
            delete(row);
        } catch (Exception e) {
            MessageDialog.error(this, "Vui lòng xoá các mô tả và phiên bản trước khi xoá sản phẩm!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        int row = table.getSelectedRow();
        if (row == -1) {
            MessageDialog.error(this, "Chưa chọn dòng để xem");
            return;
        }
        info(row);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        JTableExporter.exportJTableToExcel(table);
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropertiesActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row == -1) {
            MessageDialog.error(this, "Chưa chọn dòng để chỉnh sửa");
            return;
        }
        properties(row);
    }//GEN-LAST:event_btnPropertiesActionPerformed

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row == -1) {
            MessageDialog.error(this, "Chưa chọn dòng để chỉnh sửa");
            return;
        }
        model(row);
    }//GEN-LAST:event_btnModelActionPerformed

    private void cboSearchTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSearchTypeItemStateChanged
        // TODO add your handling code here:
        String type = (String) cboSearchType.getSelectedItem();
        list = ct.getSearchTable(txtSearch.getText(), type);
        loadTable();
    }//GEN-LAST:event_cboSearchTypeItemStateChanged

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() != MouseEvent.BUTTON3) {
            return;
        }
        JPopupMenu popup = new JPopupMenu();
        JMenuItem viewDetailsItem = new JMenuItem("Xem thông tin");
        viewDetailsItem.setIcon(new FlatSVGIcon("svg/detail16.svg"));
        JMenuItem editItem = new JMenuItem("Chỉnh sửa");
        editItem.setIcon(new FlatSVGIcon("svg/edit16.svg"));
        JMenuItem deleteItem = new JMenuItem("Xoá");
        deleteItem.setIcon(new FlatSVGIcon("svg/delete16.svg"));

        JMenuItem exportExcel = new JMenuItem("Xuất Excel");
        exportExcel.setIcon(new FlatSVGIcon("svg/export16.svg"));

        JMenuItem model = new JMenuItem("Phiên bản");
        model.setIcon(new FlatSVGIcon("svg/phienban16.svg"));

        JMenuItem properties = new JMenuItem("Thuộc tính");
        properties.setIcon(new FlatSVGIcon("svg/thuoctinh16.svg"));
        model.addActionListener((ActionEvent e) -> {
            model(table.rowAtPoint(evt.getPoint()));
        });
        properties.addActionListener((ActionEvent e) -> {
            properties(table.rowAtPoint(evt.getPoint()));
        });
        exportExcel.addActionListener((ActionEvent e) -> {
            JTableExporter.exportJTableToExcel(table);
        });
        deleteItem.addActionListener((ActionEvent e) -> {
            delete(table.rowAtPoint(evt.getPoint()));
        });
        editItem.addActionListener((ActionEvent e) -> {
            edit(table.rowAtPoint(evt.getPoint()));
        });
        viewDetailsItem.addActionListener((ActionEvent e) -> {
            info(table.rowAtPoint(evt.getPoint()));
        });
        popup.add(properties);
        popup.add(model);
        popup.add(new JSeparator());
        popup.add(viewDetailsItem);
        popup.add(editItem);
        popup.add(deleteItem);
        popup.add(new JSeparator());
        popup.add(exportExcel);
        popup.show(table, evt.getX(), evt.getY());
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnModel;
    private javax.swing.JButton btnProperties;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboSearchType;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTable;
    private javax.swing.JTable table;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
