/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package braces.gui.page;

import braces.gui.MainLayout;
import braces.gui.dialog.ColorDialog;
import braces.gui.dialog.RAMDialog;
import braces.gui.dialog.ROMDialog;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dialog;

/**
 *
 * @author Braces
 */
public class PropertiesPage extends javax.swing.JPanel {

    /**
     * Creates new form PropertiesPage
     */
    private MainLayout main;

    public PropertiesPage() {
        initComponents();
    }

    public PropertiesPage(MainLayout main) {
        initComponents();
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanel = new javax.swing.JPanel();
        btnColor = new javax.swing.JButton();
        btnRam = new javax.swing.JButton();
        btnRom = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tablePanel.setBackground(new java.awt.Color(230, 245, 245));
        tablePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 245, 245), 40));
        tablePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablePanel.setLayout(new java.awt.GridLayout(3, 1, 20, 20));

        btnColor.setFont(new java.awt.Font("Roboto Mono Medium", 0, 36)); // NOI18N
        btnColor.setForeground(new java.awt.Color(51, 51, 51));
        btnColor.setIcon(new FlatSVGIcon("svg/color.svg"));
        btnColor.setText("MÀU SẮC");
        btnColor.setBorder(null);
        btnColor.setBorderPainted(false);
        btnColor.setFocusPainted(false);
        btnColor.setIconTextGap(16);
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        tablePanel.add(btnColor);

        btnRam.setFont(new java.awt.Font("Roboto Mono Medium", 0, 36)); // NOI18N
        btnRam.setForeground(new java.awt.Color(51, 51, 51));
        btnRam.setIcon(new FlatSVGIcon("svg/ram.svg"));
        btnRam.setText("DUNG LƯỢNG RAM");
        btnRam.setBorder(null);
        btnRam.setBorderPainted(false);
        btnRam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRam.setFocusPainted(false);
        btnRam.setIconTextGap(16);
        btnRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRamActionPerformed(evt);
            }
        });
        tablePanel.add(btnRam);

        btnRom.setFont(new java.awt.Font("Roboto Mono Medium", 0, 36)); // NOI18N
        btnRom.setForeground(new java.awt.Color(51, 51, 51));
        btnRom.setIcon(new FlatSVGIcon("svg/rom.svg"));
        btnRom.setText("DUNG LƯỢNG ROM");
        btnRom.setBorder(null);
        btnRom.setBorderPainted(false);
        btnRom.setFocusPainted(false);
        btnRom.setIconTextGap(16);
        btnRom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomActionPerformed(evt);
            }
        });
        tablePanel.add(btnRom);

        add(tablePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        Dialog dialog = new ColorDialog(null, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.setResizable(false);
    }//GEN-LAST:event_btnColorActionPerformed

    private void btnRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRamActionPerformed
        Dialog dialog = new RAMDialog(null, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.setResizable(false);
    }//GEN-LAST:event_btnRamActionPerformed
    
    private void btnRomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomActionPerformed
        Dialog dialog = new ROMDialog(null, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.setResizable(false);
    }//GEN-LAST:event_btnRomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnRam;
    private javax.swing.JButton btnRom;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
