/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package braces.gui;

import braces.gui.dialog.InfoEmployeeDialog;
import braces.gui.page.ClientPage;
import braces.gui.page.EmployeePage;
import braces.gui.page.ExportHistoryPage;
import braces.gui.page.ExportPage;
import braces.gui.page.HistoryPage;
import braces.gui.page.HomePage;
import braces.gui.page.ImportPage;
import braces.gui.page.ProductPage;
import braces.gui.page.PropertiesPage;
import braces.gui.page.StatsPage;
import braces.gui.page.SupplierPage;
import braces.gui.page.WarehousePage;
import braces.util.XAuth;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Braces
 */
public class MainLayout extends javax.swing.JFrame {

    Color ACTIVE_BACKGROUND_COLOR = new Color(195, 240, 235);
    private List<JButton> listBtn;
    public MainLayout() {
        initComponents();
        setLocationRelativeTo(null);
        init();
    }
    void init() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/png/warehouse.png"));
        txtFullName.setText(XAuth.taikhoan.getTenNv());
        if (XAuth.taikhoan.getRole() == 2) {
            txtRole.setText("Người quản lý kho");
        } else txtRole.setText("Nhân viên kho");
        this.setIconImage(icon);
        listBtn = new ArrayList<>();
        listBtn.add(btnHome);
        listBtn.add(btnClient);
        listBtn.add(btnEmployee);
        listBtn.add(btnExportBill);
        listBtn.add(btnHistory);
        listBtn.add(btnImportBill);
        listBtn.add(btnWarehouse);
        listBtn.add(btnProduct);
        listBtn.add(btnStats);
        listBtn.add(btnSupplier);
        listBtn.add(btnProperties);
        this.setPanel(new HomePage());
        for (JButton item : listBtn) {
            item.getModel().addChangeListener((ChangeEvent e) -> {
                ButtonModel model = (ButtonModel) e.getSource();
                if (model.isSelected()) {
                    item.setBackground(ACTIVE_BACKGROUND_COLOR);
                }
            });
        }
        btnHome.setSelected(true);
        if (XAuth.taikhoan.getRole() == 1) {
            btnProduct.setEnabled(false);
            btnStats.setEnabled(false);
            btnProperties.setEnabled( false);
            btnHistory.setEnabled(false);
            btnEmployee.setEnabled(false);
        }
    }

    public void setPanel(JPanel pn) {
        mainContent.removeAll();
        mainContent.add(pn).setVisible(true);
        mainContent.repaint();
        mainContent.validate();
    }

    void resetBtn() {
        for (JButton item : listBtn) {
            item.setSelected(false);
            item.setBackground(Color.WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContent = new javax.swing.JPanel();
        leftContent = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnStats = new javax.swing.JButton();
        btnWarehouse = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnProperties = new javax.swing.JButton();
        btnImportBill = new javax.swing.JButton();
        btnExportBill = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnEmployee = new javax.swing.JButton();
        btnClient = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInfo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtFullName = new javax.swing.JLabel();
        txtRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kho hàng");
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(400, 800));

        mainContent.setBackground(new java.awt.Color(243, 255, 255));
        mainContent.setPreferredSize(new java.awt.Dimension(1230, 800));
        mainContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        leftContent.setBackground(new java.awt.Color(230, 245, 245));
        leftContent.setPreferredSize(new java.awt.Dimension(250, 800));

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 2, true));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 800));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(220, 550));

        itemPanel.setBackground(new java.awt.Color(255, 255, 255));
        itemPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
        itemPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        itemPanel.setPreferredSize(new java.awt.Dimension(250, 500));

        btnHome.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnHome.setIcon(new FlatSVGIcon("svg/home.svg"));
        btnHome.setText("Trang chủ");
        btnHome.setBorderPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);
        btnHome.setFocusable(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHome.setIconTextGap(16);
        btnHome.setPreferredSize(new java.awt.Dimension(226, 46));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        itemPanel.add(btnHome);

        btnProduct.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnProduct.setIcon(new FlatSVGIcon("svg/product.svg"));
        btnProduct.setText("Sản phẩm");
        btnProduct.setBorderPainted(false);
        btnProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduct.setFocusPainted(false);
        btnProduct.setFocusable(false);
        btnProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnProduct.setIconTextGap(16);
        btnProduct.setPreferredSize(new java.awt.Dimension(226, 46));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        itemPanel.add(btnProduct);

        btnStats.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnStats.setIcon(new FlatSVGIcon("svg/stats.svg"));
        btnStats.setText("Thống kê");
        btnStats.setBorderPainted(false);
        btnStats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStats.setFocusPainted(false);
        btnStats.setFocusable(false);
        btnStats.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnStats.setIconTextGap(16);
        btnStats.setPreferredSize(new java.awt.Dimension(226, 46));
        btnStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatsActionPerformed(evt);
            }
        });
        itemPanel.add(btnStats);

        btnWarehouse.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnWarehouse.setIcon(new FlatSVGIcon("svg/warehouse.svg"));
        btnWarehouse.setText("Kho hàng");
        btnWarehouse.setBorderPainted(false);
        btnWarehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWarehouse.setFocusPainted(false);
        btnWarehouse.setFocusable(false);
        btnWarehouse.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnWarehouse.setIconTextGap(16);
        btnWarehouse.setPreferredSize(new java.awt.Dimension(226, 46));
        btnWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarehouseActionPerformed(evt);
            }
        });
        itemPanel.add(btnWarehouse);

        jSeparator2.setPreferredSize(new java.awt.Dimension(230, 2));
        itemPanel.add(jSeparator2);

        btnProperties.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnProperties.setIcon(new FlatSVGIcon("svg/prop.svg"));
        btnProperties.setText("Thuộc tính chung");
        btnProperties.setBorderPainted(false);
        btnProperties.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProperties.setFocusPainted(false);
        btnProperties.setFocusable(false);
        btnProperties.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnProperties.setIconTextGap(16);
        btnProperties.setPreferredSize(new java.awt.Dimension(226, 46));
        btnProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropertiesActionPerformed(evt);
            }
        });
        itemPanel.add(btnProperties);

        btnImportBill.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnImportBill.setIcon(new FlatSVGIcon("svg/import.svg"));
        btnImportBill.setText("Phiếu nhập");
        btnImportBill.setBorderPainted(false);
        btnImportBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImportBill.setFocusPainted(false);
        btnImportBill.setFocusable(false);
        btnImportBill.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnImportBill.setIconTextGap(16);
        btnImportBill.setPreferredSize(new java.awt.Dimension(226, 46));
        btnImportBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportBillActionPerformed(evt);
            }
        });
        itemPanel.add(btnImportBill);

        btnExportBill.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnExportBill.setIcon(new FlatSVGIcon("svg/export.svg"));
        btnExportBill.setText("Phiếu xuất");
        btnExportBill.setBorderPainted(false);
        btnExportBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportBill.setFocusPainted(false);
        btnExportBill.setFocusable(false);
        btnExportBill.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnExportBill.setIconTextGap(16);
        btnExportBill.setPreferredSize(new java.awt.Dimension(226, 46));
        btnExportBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportBillActionPerformed(evt);
            }
        });
        itemPanel.add(btnExportBill);

        btnHistory.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnHistory.setIcon(new FlatSVGIcon("svg/history.svg"));
        btnHistory.setText("Lịch sử");
        btnHistory.setBorderPainted(false);
        btnHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistory.setFocusPainted(false);
        btnHistory.setFocusable(false);
        btnHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHistory.setIconTextGap(16);
        btnHistory.setPreferredSize(new java.awt.Dimension(226, 46));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        itemPanel.add(btnHistory);

        jSeparator3.setPreferredSize(new java.awt.Dimension(230, 2));
        itemPanel.add(jSeparator3);

        btnEmployee.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnEmployee.setIcon(new FlatSVGIcon("svg/employee.svg"));
        btnEmployee.setText("Nhân viên");
        btnEmployee.setBorderPainted(false);
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.setFocusPainted(false);
        btnEmployee.setFocusable(false);
        btnEmployee.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEmployee.setIconTextGap(16);
        btnEmployee.setPreferredSize(new java.awt.Dimension(226, 46));
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        itemPanel.add(btnEmployee);

        btnClient.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnClient.setIcon(new FlatSVGIcon("svg/client.svg"));
        btnClient.setText("Khách hàng");
        btnClient.setBorderPainted(false);
        btnClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClient.setFocusPainted(false);
        btnClient.setFocusable(false);
        btnClient.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnClient.setIconTextGap(16);
        btnClient.setPreferredSize(new java.awt.Dimension(226, 46));
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        itemPanel.add(btnClient);

        btnSupplier.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnSupplier.setIcon(new FlatSVGIcon("svg/supplier.svg"));
        btnSupplier.setText("Nhà cung cấp");
        btnSupplier.setBorderPainted(false);
        btnSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupplier.setFocusPainted(false);
        btnSupplier.setFocusable(false);
        btnSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSupplier.setIconTextGap(16);
        btnSupplier.setPreferredSize(new java.awt.Dimension(226, 46));
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        itemPanel.add(btnSupplier);

        jScrollPane1.setViewportView(itemPanel);

        sidebarPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 2, true));
        infoPanel.setForeground(new java.awt.Color(243, 243, 243));
        infoPanel.setPreferredSize(new java.awt.Dimension(200, 80));
        infoPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(64, 80));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnInfo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnInfo.setIcon(new FlatSVGIcon("svg/man.svg"));
        btnInfo.setBorderPainted(false);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.setFocusPainted(false);
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfo.setPreferredSize(new java.awt.Dimension(90, 90));
        btnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        jPanel2.add(btnInfo, java.awt.BorderLayout.CENTER);

        infoPanel.add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtFullName.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtFullName.setText("Nguyễn Văn A");

        txtRole.setFont(new java.awt.Font("Roboto Light", 2, 13)); // NOI18N
        txtRole.setText("Nhân viên Quản lý");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRole, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        infoPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout leftContentLayout = new javax.swing.GroupLayout(leftContent);
        leftContent.setLayout(leftContentLayout);
        leftContentLayout.setHorizontalGroup(
            leftContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftContentLayout.createSequentialGroup()
                .addGroup(leftContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftContentLayout.setVerticalGroup(
            leftContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftContentLayout.createSequentialGroup()
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );

        getContentPane().add(leftContent, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        setPanel(new HomePage());
        resetBtn();
        btnHome.setSelected(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        setPanel(new ProductPage(this));
        resetBtn();
        btnProduct.setSelected(true);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarehouseActionPerformed
        setPanel(new WarehousePage());
        resetBtn();
        btnWarehouse.setSelected(true);
    }//GEN-LAST:event_btnWarehouseActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        setPanel(new ClientPage());
        resetBtn();
        btnClient.setSelected(true);
    }//GEN-LAST:event_btnClientActionPerformed

    private void btnImportBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportBillActionPerformed
        setPanel(new ImportPage(this));
        resetBtn();
        btnImportBill.setSelected(true);
    }//GEN-LAST:event_btnImportBillActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        setPanel(new SupplierPage());
        resetBtn();
        btnSupplier.setSelected(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        setPanel(new EmployeePage());
        resetBtn();
        btnEmployee.setSelected(true);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
  Dialog dialog = new InfoEmployeeDialog(null, true, XAuth.taikhoan);
        dialog.setLocationRelativeTo(null);

        dialog.setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnExportBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportBillActionPerformed
        // TODO add your handling code here:
        setPanel(new ExportPage(this));
        resetBtn();
        btnExportBill.setSelected(true);
    }//GEN-LAST:event_btnExportBillActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        setPanel(new HistoryPage());
        resetBtn();
        btnHistory.setSelected(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsActionPerformed
        // TODO add your handling code here:
        setPanel(new StatsPage());
        resetBtn();
        btnStats.setSelected(true);
    }//GEN-LAST:event_btnStatsActionPerformed

    private void btnPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropertiesActionPerformed
        // TODO add your handling code here:
        setPanel(new PropertiesPage());
        resetBtn();
        btnProperties.setSelected(true);
    }//GEN-LAST:event_btnPropertiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLaf.registerCustomDefaultsSource("style");

        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExportBill;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnImportBill;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnProperties;
    private javax.swing.JButton btnStats;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnWarehouse;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel leftContent;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel txtFullName;
    private javax.swing.JLabel txtRole;
    // End of variables declaration//GEN-END:variables
}
