package braces.gui.dialog;

import braces.controller.impl.CTPhieuNhapControllerImpl;
import braces.controller.impl.NhaCungCapControllerImpl;
import braces.controller.impl.PhienBanControllerImpl;
import braces.controller.impl.SanPhamControllerImpl;
import braces.controller.impl.TaiKhoanControllerImpl;
import braces.dao.impl.CTPhieuNhapDAOImpl;
import braces.dao.impl.NhaCungCapDAOImpl;
import braces.dao.impl.PhienBanDAOImpl;
import braces.dao.impl.SanPhamDAOImpl;
import braces.dao.impl.TaiKhoanDAOImpl;
import braces.entity.CTPhieuNhap;
import braces.entity.PhienBan;
import braces.entity.PhieuNhap;
import braces.entity.SanPham;
import braces.util.Formatter;
import braces.util.JTableUtilities;
import braces.util.PdfGenerator;
import braces.util.XIcon;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Braces
 */
public class DetailImportBill extends javax.swing.JDialog {

    /**
     * Creates new form DetailImportBill
     */
    SanPhamControllerImpl ctSP = new SanPhamControllerImpl(new SanPhamDAOImpl());
    TaiKhoanControllerImpl ctTK = new TaiKhoanControllerImpl(new TaiKhoanDAOImpl());
    PhieuNhap phieuNhap;
    List<CTPhieuNhap> listCT = new ArrayList<>();
    PhienBanControllerImpl ctPB = new PhienBanControllerImpl(new PhienBanDAOImpl());
    CTPhieuNhapControllerImpl ctPN = new CTPhieuNhapControllerImpl(new CTPhieuNhapDAOImpl());
    NhaCungCapControllerImpl ctNCC = new NhaCungCapControllerImpl(new NhaCungCapDAOImpl());

    public DetailImportBill(java.awt.Frame parent, boolean modal, PhieuNhap phieuNhap) {
        super(parent, modal);
        this.phieuNhap = phieuNhap;
        initComponents();
        init();
    }

    void init() {
        JTableUtilities.setCellsAlignment(table, SwingConstants.CENTER);
        txtMaPhieu.setText(String.valueOf(phieuNhap.getMaPhieuNhap()));
        txtNCC.setText(ctNCC.getById(phieuNhap.getMaNhaCungCap()).get().getTenNhaCungCap());
        txtTenNV.setText(ctTK.getById(phieuNhap.getNguoiTaoPhieuNhap()).get().getTenNv());
        txtTong.setText(Formatter.formatVND((double) phieuNhap.getTongTien()));
        lblDate.setText("Ngày tạo: " + Formatter.FormatDate(phieuNhap.getThoiGian()));
        loadTable();
    }

    void loadTable() {
        listCT = ctPN.getByPhieuNhap(phieuNhap.getMaPhieuNhap());
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int count = 0;
        for (CTPhieuNhap ct : listCT) {
            count++;
            PhienBan pb = ctPB.getById(ct.getMaPhienBan()).get();
            Object[] rowData = {
                count,
                ctSP.getById(pb.getMaSP()).get().getTenSanPham(),
                ct.getMaPhienBan(), ct.getSoLuong(),
                Formatter.formatVND((double) ct.getDonGia())
            };
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hoaDonPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMaPhieu = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNCC = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        lblHinhAnh = new javax.swing.JLabel();
        tableItemPanel = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        lblThuoc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết phiếu nhập");
        setPreferredSize(new java.awt.Dimension(1250, 672));

        jPanel15.setBackground(new java.awt.Color(0, 153, 153));
        jPanel15.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel15.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CHI TIẾT PHIẾU NHẬP");
        jLabel8.setPreferredSize(new java.awt.Dimension(149, 40));
        jPanel15.add(jLabel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        hoaDonPanel.setBackground(new java.awt.Color(255, 255, 255));
        hoaDonPanel.setPreferredSize(new java.awt.Dimension(1200, 80));
        hoaDonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 16));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(340, 40));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Mã hóa đơn ");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel7.add(jLabel4);

        txtMaPhieu.setEditable(false);
        txtMaPhieu.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtMaPhieu.setText("Z2NX8CN1A");
        txtMaPhieu.setFocusable(false);
        txtMaPhieu.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel7.add(txtMaPhieu);

        hoaDonPanel.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(440, 40));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Nhà cung cấp");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel9.add(jLabel5);

        txtNCC.setEditable(false);
        txtNCC.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNCC.setText("Nguyễn Văn A");
        txtNCC.setFocusable(false);
        txtNCC.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel9.add(txtNCC);

        hoaDonPanel.add(jPanel9);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(340, 40));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Tên nhân viên");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel11.add(jLabel7);

        txtTenNV.setEditable(false);
        txtTenNV.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTenNV.setText("Vũ Nương");
        txtTenNV.setFocusable(false);
        txtTenNV.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel11.add(txtTenNV);

        hoaDonPanel.add(jPanel11);

        jPanel2.add(hoaDonPanel, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 100));

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));
        imagePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 2, true));
        imagePanel.setPreferredSize(new java.awt.Dimension(300, 300));
        imagePanel.setLayout(new java.awt.BorderLayout());

        lblHinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHinhAnh.setPreferredSize(new java.awt.Dimension(200, 100));
        imagePanel.add(lblHinhAnh, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        tableItemPanel.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(0, 153, 153));
        jPanel16.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel16.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel16.setLayout(new java.awt.BorderLayout());

        lblThuoc.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblThuoc.setForeground(new java.awt.Color(255, 255, 255));
        lblThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThuoc.setText("Thông tin sản phẩm");
        jPanel16.add(lblThuoc, java.awt.BorderLayout.CENTER);

        tableItemPanel.add(jPanel16, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Mã phiên bản", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        tableItemPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 60));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("Tổng hóa đơn:");
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel12.add(jLabel9);

        txtTong.setEditable(false);
        txtTong.setFont(new java.awt.Font("Roboto Mono Medium", 0, 14)); // NOI18N
        txtTong.setForeground(new java.awt.Color(255, 51, 0));
        txtTong.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtTong.setText("1000000");
        txtTong.setToolTipText("");
        txtTong.setFocusable(false);
        txtTong.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel12.add(txtTong);

        lblDate.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 0, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDate.setText("Ngày tạo:");
        lblDate.setToolTipText("");
        lblDate.setPreferredSize(new java.awt.Dimension(180, 17));
        jPanel12.add(lblDate);

        jPanel1.add(jPanel12);

        tableItemPanel.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(tableItemPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 5));

        btnHuy.setBackground(new java.awt.Color(255, 102, 102));
        btnHuy.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY BỎ");
        btnHuy.setBorderPainted(false);
        btnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHuy.setFocusPainted(false);
        btnHuy.setFocusable(false);
        btnHuy.setPreferredSize(new java.awt.Dimension(200, 40));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel8.add(btnHuy);

        btnPrint.setBackground(new java.awt.Color(0, 153, 153));
        btnPrint.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("IN HOÁ ĐƠN");
        btnPrint.setBorderPainted(false);
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.setFocusPainted(false);
        btnPrint.setFocusable(false);
        btnPrint.setPreferredSize(new java.awt.Dimension(200, 40));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel8.add(btnPrint);

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file PDF");
        fileChooser.setSelectedFile(new File("phieu_nhap_" + phieuNhap.getMaPhieuNhap() + ".pdf"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.toLowerCase().endsWith(".pdf")) {
                filePath += ".pdf";
            }
            try {
                PdfGenerator.generatePhieuNhap(
                        txtMaPhieu.getText(),
                        txtNCC.getText(),
                        txtTenNV.getText(),
                        lblDate.getText().replace("Ngày tạo: ", ""),
                        txtTong.getText(),
                        table,
                        filePath
                );

            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        PhienBan pb = ctPB.getById(table.getValueAt(table.getSelectedRow(), 2).toString()).get();
        SanPham sp = ctSP.getById(pb.getMaSP()).get();
        XIcon.setIcon(lblHinhAnh, "src/main/resources/img/" + sp.getHinhAnh());

    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailImportBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailImportBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailImportBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailImportBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnPrint;
    private javax.swing.JPanel hoaDonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblThuoc;
    private javax.swing.JTable table;
    private javax.swing.JPanel tableItemPanel;
    private javax.swing.JTextField txtMaPhieu;
    private javax.swing.JTextField txtNCC;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
