/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package braces.gui.dialog;

import braces.controller.impl.DungLuongRAMControllerImpl;
import braces.controller.impl.DungLuongROMControllerImpl;
import braces.controller.impl.MauSacControllerImpl;
import braces.controller.impl.PhienBanControllerImpl;
import braces.dao.impl.DungLuongRAMDAOImpl;
import braces.dao.impl.DungLuongROMDAOImpl;
import braces.dao.impl.MauSacDAOImpl;
import braces.dao.impl.PhienBanDAOImpl;
import braces.entity.DungLuongRAM;
import braces.entity.DungLuongROM;
import braces.entity.MauSac;
import braces.entity.PhienBan;
import braces.entity.ThuocTinhSanPham;
import braces.util.Formatter;
import braces.util.JTableUtilities;
import braces.util.MessageDialog;
import braces.util.Validation;
import com.sun.jdi.connect.Connector;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

public class ModelDialog extends javax.swing.JDialog {

    MauSacControllerImpl ctMau = new MauSacControllerImpl(new MauSacDAOImpl());
    DungLuongRAMControllerImpl ctRAM = new DungLuongRAMControllerImpl(new DungLuongRAMDAOImpl());
    DungLuongROMControllerImpl ctROM = new DungLuongROMControllerImpl(new DungLuongROMDAOImpl());
    PhienBanControllerImpl ct = new PhienBanControllerImpl(new PhienBanDAOImpl());
    List<MauSac> listMauSac = List.of();
    List<DungLuongRAM> listRAM = List.of();
    List<DungLuongROM> listROM = List.of();
    List<PhienBan> list = List.of();
    int maSP;

    public ModelDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        init();
    }

    void init() {
        JTableUtilities.setCellsAlignment(table, SwingConstants.CENTER);

        list = ct.getBySanPham(maSP);
        lblTitle.setText("Phiên bản sản phẩm: " + maSP);
        setLocationRelativeTo(null);
        loadColor();
        loadRAM();
        loadROM();
        loadTable();
        clear();
    }

    public ModelDialog(java.awt.Frame parent, boolean modal, int maSP) {
        super(parent, modal);
        this.maSP = maSP;
        initComponents();

        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        cboColor = new javax.swing.JComboBox<>();
        cboRAM = new javax.swing.JComboBox<>();
        cboROM = new javax.swing.JComboBox<>();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaXuat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phiên bản sản phẩm");
        setMaximumSize(new java.awt.Dimension(1250, 700));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setPreferredSize(new java.awt.Dimension(1250, 700));

        jPanel15.setBackground(new java.awt.Color(0, 153, 153));
        jPanel15.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel15.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PHIÊN BẢN SẢN PHẨM");
        jPanel15.add(lblTitle, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1150, 120));
        jPanel4.setLayout(new java.awt.GridLayout(2, 7, 5, 0));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Mã phiên bản");
        jPanel4.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Số lượng");
        jPanel4.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Màu sắc");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("RAM");
        jPanel4.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("ROM");
        jPanel4.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Giá nhập");
        jPanel4.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Giá xuất");
        jPanel4.add(jLabel7);

        txtMa.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });
        jPanel4.add(txtMa);

        txtSoLuong.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        jPanel4.add(txtSoLuong);

        cboColor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboColorActionPerformed(evt);
            }
        });
        jPanel4.add(cboColor);

        cboRAM.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cboRAM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cboRAM);

        cboROM.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cboROM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cboROM);

        txtGiaNhap.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel4.add(txtGiaNhap);

        txtGiaXuat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel4.add(txtGiaXuat);

        jPanel1.add(jPanel4);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 406));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiên bản", "Số lượng", "Màu sắc", "RAM", "ROM", "Giá nhập", "Giá xuất"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 5));

        btnRemove.setBackground(new java.awt.Color(255, 102, 102));
        btnRemove.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("XÓA");
        btnRemove.setBorderPainted(false);
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.setFocusPainted(false);
        btnRemove.setFocusable(false);
        btnRemove.setPreferredSize(new java.awt.Dimension(120, 40));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel8.add(btnRemove);

        btnUpdate.setBackground(new java.awt.Color(255, 204, 51));
        btnUpdate.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("SỬA");
        btnUpdate.setBorderPainted(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);
        btnUpdate.setFocusable(false);
        btnUpdate.setPreferredSize(new java.awt.Dimension(120, 40));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel8.add(btnUpdate);

        btnAdd.setBackground(new java.awt.Color(0, 204, 102));
        btnAdd.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("THÊM");
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setFocusable(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(120, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel8.add(btnAdd);

        btnClear.setBackground(new java.awt.Color(0, 102, 255));
        btnClear.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("TẠO MỚI");
        btnClear.setBorderPainted(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        btnClear.setFocusable(false);
        btnClear.setPreferredSize(new java.awt.Dimension(120, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel8.add(btnClear);

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void loadTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (PhienBan pb : list) {
            Object[] row = {pb.getMaPhienBanSP(), pb.getSoLuongTon(),
                ctMau.getById(pb.getMauSac()).get().getTenMau(),
                ctRAM.getById(pb.getMaRam()).get().getKichThuocRam() + " GB",
                ctROM.getById(pb.getMaRom()).get().getKichThuocRom() + " GB",
               Formatter.formatVND((double) pb.getGiaNhap()),  Formatter.formatVND((double) pb.getGiaBan())
            };
            model.addRow(row);
        }
    }

    void loadColor() {
        listMauSac = ctMau.getAll();
        String[] searchType = new String[listMauSac.size()];
        for (int i = 0; i < listMauSac.size(); i++) {
            searchType[i] = listMauSac.get(i).getTenMau();
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(searchType);
        cboColor.setModel(model);
    }

    PhienBan getForm() {
        PhienBan pb = new PhienBan();
        pb.setGiaBan(Integer.valueOf(txtGiaXuat.getText()));
        pb.setGiaNhap(Integer.valueOf(txtGiaNhap.getText()));
        pb.setMaPhienBanSP(txtMa.getText());
        pb.setMaRam(listRAM.get(cboRAM.getSelectedIndex()).getMaRam());
        pb.setMaRom(listROM.get(cboROM.getSelectedIndex()).getMaRom());
        pb.setMauSac(listMauSac.get(cboColor.getSelectedIndex()).getMaMau());
        pb.setSoLuongTon(Integer.valueOf(txtSoLuong.getText()));
        pb.setMaSP(this.maSP);
        return pb;
    }
    void clear() {
        table.clearSelection();
        txtMa.setText("");
        txtSoLuong.setText("");
        txtGiaNhap.setText("");
        txtGiaXuat.setText("");
        cboColor.setSelectedIndex(-1);
        cboRAM.setSelectedIndex(-1);
        cboROM.setSelectedIndex(-1);
        setActiveButton(true);
    }

    void setForm(PhienBan pb) {
        txtMa.setText(pb.getMaPhienBanSP());
        txtGiaNhap.setText(String.valueOf(pb.getGiaNhap()));
        txtGiaXuat.setText(String.valueOf(pb.getGiaBan()));
        txtSoLuong.setText(String.valueOf(pb.getSoLuongTon()));
        int index = 0;
        for (MauSac ms : listMauSac) {
            if (pb.getMauSac() == ms.getMaMau()) {
                index = listMauSac.indexOf(ms);
            }
        }
        cboColor.setSelectedIndex(index);
        index = 0;
        for (DungLuongRAM ram : listRAM) {
            if (pb.getMaRam() == ram.getMaRam()) {
                index = listRAM.indexOf(ram);
            }
        }
        cboRAM.setSelectedIndex(index);

        index = 0;
        for (DungLuongROM rom : listROM) {
            if (pb.getMaRom() == rom.getMaRom()) {
                index = listROM.indexOf(rom);
            }
        }
        cboROM.setSelectedIndex(index);

    }

    void loadRAM() {
        listRAM = ctRAM.getAll();
        String[] searchType = new String[listRAM.size()];
        for (int i = 0; i < listRAM.size(); i++) {
            searchType[i] = String.valueOf(listRAM.get(i).getKichThuocRam()) + " GB";
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(searchType);
        cboRAM.setModel(model);
    }
    boolean validateForm() {
         if (Validation.isEmpty(txtMa.getText())) {
             MessageDialog.warring(this, "Mã không được để trống");
             return false;
         }
         
         if (Validation.isEmpty(txtSoLuong.getText())) {
             MessageDialog.warring(this, "Số lượng không được để trống");
             return false;
         }
         
         if (Validation.isEmpty(txtGiaNhap.getText())) {
             MessageDialog.warring(this, "Giá nhập không được để trống");
             return false;
         }
         
         if (Validation.isEmpty(txtGiaXuat.getText())) {
             MessageDialog.warring(this, "Giá xuất không được để trống");
             return false;
         }
         if (Validation.isNumber(txtSoLuong.getText())) {
             MessageDialog.warring(this, "Số lượng phải là số");
         }
         
         if (Validation.isNumber(txtGiaNhap.getText())) {
             MessageDialog.warring(this, "Giá nhập phải là số");
         }
         
         if (Validation.isNumber(txtGiaXuat.getText())) {
             MessageDialog.warring(this, "Giá xuất phải là số");
         }
         if (cboColor.getSelectedIndex() < 0) {
             MessageDialog.warring(this, "Vui lòng chọn màu sắc");
         }
         
         if (cboRAM.getSelectedIndex() < 0) {
             MessageDialog.warring(this, "Vui lòng chọn dung lượng RAM");
         }
         
         if (cboROM.getSelectedIndex() < 0) {
             MessageDialog.warring(this, "Vui lòng chọn dung lượng ROM");
         }
         return true;
    }
    void loadROM() {

        listROM = ctROM.getAll();
        String[] searchType = new String[listROM.size()];
        for (int i = 0; i < listROM.size(); i++) {
            searchType[i] = String.valueOf(listROM.get(i).getKichThuocRom()) + " GB";
        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(searchType);
        cboROM.setModel(model);
    }

    void setActiveButton(boolean active) {
        btnAdd.setEnabled(active);
        btnRemove.setEnabled(!active);
        btnUpdate.setEnabled(!active);
        txtMa.setEditable(active);
    }
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        try {
            String id = list.get(table.getSelectedRow()).getMaPhienBanSP();
            if (MessageDialog.confirm(this, "Bạn có chắc chắn xóa dòng này?", "Xóa")) {
                ct.deleteById(id);
                MessageDialog.info(this, "Xóa thành công!");
                init();
            }
        } catch (Exception e) {
            MessageDialog.error(this, "Vui lòng chọn dòng cần thực hiện!");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!validateForm()) return;
        ct.save(getForm());
        MessageDialog.info(this, "Sửa thành công");
        init();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!validateForm()) return;
        ct.save(getForm());
        MessageDialog.info(this, "Thêm thành công");
        init();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void cboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboColorActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        setActiveButton(false);
        int row = table.getSelectedRow();
        setForm(list.get(row));
    }//GEN-LAST:event_tableMouseClicked

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModelDialog dialog = new ModelDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboColor;
    private javax.swing.JComboBox<String> cboRAM;
    private javax.swing.JComboBox<String> cboROM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtGiaXuat;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
